#!/bin/bash
set -eu -o pipefail

# DATABASE_NAME
# DATABASE_NAME_TESTING
# DB_HOST
# DB_PASSWORD

echo "CREATE DATABASE IF NOT EXISTS ${DB_NAME};CREATE DATABASE IF NOT EXISTS ${DB_NAME_TESTING};" | mysql -h ${DB_HOST} -p${DB_PASSWORD}
