FROM mhart/alpine-node:14

WORKDIR /frontend

EXPOSE 3200
EXPOSE 3201
EXPOSE 82
EXPOSE 8443

# ADD /frontend /frontend

# this needs to be here, so that when `yarn --silent` runs it will have the correct peer deps.
# RUN cd client && yarn add node-sass@4.14.1

# RUN yarn --silent

# RUN yarn run build